//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilim_EF {
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
	using System.Data.Entity.Core.Objects;
	using System.Linq;

	public partial class PilimEntities : DbContext {
		public PilimEntities()
			: base("name=PilimEntities") {
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder) {
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Cliente> Cliente { get; set; }
		public virtual DbSet<Contacto> Contacto { get; set; }
		public virtual DbSet<Email> Email { get; set; }
		public virtual DbSet<Instrumento> Instrumento { get; set; }
		public virtual DbSet<MerFin> MerFin { get; set; }
		public virtual DbSet<Portfolio> Portfolio { get; set; }
		public virtual DbSet<Telefone> Telefone { get; set; }
		public virtual DbSet<Posições> Posições { get; set; }
		public virtual DbSet<RegDiaInst> RegDiaInst { get; set; }
		public virtual DbSet<RegDiaMerFin> RegDiaMerFin { get; set; }
		public virtual DbSet<Triplos> Triplos { get; set; }

		[DbFunction("PilimEntities", "fListaPortfolio")]
		public virtual IQueryable<fListaPortfolio_Result> fListaPortfolio(Nullable<int> ccT, string nomeT) {

			var ccTParameter = ccT.HasValue ?
				new ObjectParameter("ccT", ccT) :
				new ObjectParameter("ccT", typeof(int));

			var nomeTParameter = nomeT != null ?
				new ObjectParameter("nomeT", nomeT) :
				new ObjectParameter("nomeT", typeof(string));

			return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fListaPortfolio_Result>("[PilimEntities].[fListaPortfolio](@ccT, @nomeT)", ccTParameter, nomeTParameter);
		}

		public virtual int InserçãoDeRegistosDiáriosAutomáticos() {
			return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserçãoDeRegistosDiáriosAutomáticos");
		}

		public virtual int p_actualizaDadosInstrumentos(string isinT) {
			var isinTParameter = isinT != null ?
				new ObjectParameter("isinT", isinT) :
				new ObjectParameter("isinT", typeof(string));

			return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_actualizaDadosInstrumentos", isinTParameter);
		}

		public virtual int p_actualizaValorDiario() {
			return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_actualizaValorDiario");
		}
	}
}
