//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilimFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int cc { get; set; }
        public int cod_un { get; set; }
        public string endereço { get; set; }
    
        public virtual Contacto Contacto { get; set; }
    }
}
