//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilimFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrumento()
        {
            this.Posições = new HashSet<Posições>();
            this.RegDiaInsts = new HashSet<RegDiaInst>();
            this.MerFins = new HashSet<MerFin>();
        }
    
        public string isin { get; set; }
        public string descrição { get; set; }
        public float val_var_dia { get; set; }
        public float val_at { get; set; }
        public float med_6_mes_val_fe { get; set; }
        public float val_var_6_mes { get; set; }
        public float perc_var_dia { get; set; }
        public float perc_var_6_mes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posições> Posições { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegDiaInst> RegDiaInsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerFin> MerFins { get; set; }
    }
}
