//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilimFramework.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TL51N_3Entities7 : DbContext
    {
        public TL51N_3Entities7()
            : base("name=TL51N_3Entities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Contacto> Contactoes { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Instrumento> Instrumentoes { get; set; }
        public virtual DbSet<MerFin> MerFins { get; set; }
        public virtual DbSet<Telefone> Telefones { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Posições> Posições { get; set; }
        public virtual DbSet<RegDiaInst> RegDiaInsts { get; set; }
        public virtual DbSet<RegDiaMerFin> RegDiaMerFins { get; set; }
        public virtual DbSet<Triplo> Triplos { get; set; }
    
        [DbFunction("TL51N_3Entities7", "udfProductInYear")]
        public virtual IQueryable<udfProductInYear_Result> udfProductInYear(Nullable<int> ccT, string nomeT)
        {
            var ccTParameter = ccT.HasValue ?
                new ObjectParameter("ccT", ccT) :
                new ObjectParameter("ccT", typeof(int));
    
            var nomeTParameter = nomeT != null ?
                new ObjectParameter("nomeT", nomeT) :
                new ObjectParameter("nomeT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udfProductInYear_Result>("[TL51N_3Entities7].[udfProductInYear](@ccT, @nomeT)", ccTParameter, nomeTParameter);
        }
    
        public virtual int InserçãoDeRegistosDiáriosAutomáticos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserçãoDeRegistosDiáriosAutomáticos");
        }
    
        public virtual int p_actualizaDadosInstrumentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_actualizaDadosInstrumentos");
        }
    
        public virtual int p_actualizaValorDiario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_actualizaValorDiario");
        }
    }
}
