//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilimFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegDiaMerFin
    {
        public int cod_un { get; set; }
        public System.DateTime dat { get; set; }
        public float var_dia { get; set; }
        public float val_ab { get; set; }
        public float int_mer { get; set; }
    
        public virtual MerFin MerFin { get; set; }
    }
}
