//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilimFramework.DataProvider.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto : IEntity {
        public int cc { get; set; }
        public int cod_un { get; set; }
        public string descrição { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Email Email { get; set; }
        public virtual Telefone Telefone { get; set; }
    }
}
