//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilimFramework.DataProvider.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posições : IEntity {
        public int cc { get; set; }
        public string nome { get; set; }
        public string isin { get; set; }
        public int qtd { get; set; }
    
        public virtual Instrumento Instrumento { get; set; }
        public virtual Portfolio Portfolio { get; set; }
    }
}
